# vi: set ft=yaml ts=2 sw=2 sts=0 et:

version: '2'

services:
  jenkins:
    build: .
    container_name: jenkins
    restart: always
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /dev/urandom:/dev/random
    environment:
      - JAVA_OPTS='-Djava.awt.headless=true -Duser.timezone=Asia/Tokyo -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8'
      - DOCKER_HOST=tcp://dind:2375
      - VIRTUAL_HOST=jenkins.toraja.klab.org
      - VIRTUAL_PORT=8080
    networks:
      default:
      bridge:
  dind:
    image: docker:dind
    container_name: dind
    privileged: true
    restart: always
    volumes:
      - ./dind:/var/lib/docker
      - /var/jenkins_home:/var/jenkins_home

networks:
  default:
  bridge:
    external:
      name: dockernginxproxy_default

